CREATE TABLE
    FUTURE_FAMILY_FACTOR
    (
        FUTURE_FAMILY_ID NVARCHAR2(10) NOT NULL,
        FACTOR_ID INTEGER NOT NULL,
        EXPOSURE_EXPRESSION_ID INTEGER NOT NULL,
        RMS_ID NUMBER(38) NOT NULL,
        PRIMARY KEY (RMS_ID, FUTURE_FAMILY_ID, FACTOR_ID),
        CONSTRAINT FUTURE_FAMILY_FACTOR_FK1 FOREIGN KEY (RMS_ID) REFERENCES RISK_MODEL_SERIE
        (SERIAL_ID)
    );