DROP TABLE rms_statistics CASCADE CONSTRAINTS;
CREATE TABLE rms_statistics
(
	rms_id		INT NOT NULL,
	dt		DATE NOT NULL,
	adjRsquared	NUMBER,
        pctgvar         NUMBER,
	PRIMARY KEY (rms_id, dt)
) NOLOGGING
  TABLESPACE gmdl_rms_main;

DROP TABLE RMS_STATISTICS_INTERNAL CASCADE CONSTRAINTS;
CREATE TABLE MODELDB_GLOBAL.RMS_STATISTICS_INTERNAL ( 
    RMS_ID     	NUMBER(38,0) NOT NULL,
    DT         	DATE NOT NULL,
    ADJRSQUARED	NUMBER NULL,
    PCTGVAR    	NUMBER NULL,
    PRIMARY KEY(RMS_ID,DT)
	NOT DEFERRABLE
	 VALIDATE
)
NOLOGGING
TABLESPACE gmdl_rms_main;