
DROP TABLE SUB_ISSUE_FUNDAMENTAL_DATA CASCADE CONSTRAINTS

CREATE TABLE MODELDB_GLOBAL.SUB_ISSUE_FUNDAMENTAL_DATA ( 
	SUB_ISSUE_ID	NVARCHAR2(12) NOT NULL,
	ITEM_CODE_ID   	NUMBER(38) NOT NULL,
	DT          	DATE NOT NULL,
	VALUE       	NUMBER NOT NULL,
	CURRENCY_ID 	NUMBER(38) NOT NULL,
        FISCAL_YEAR_END INT NOT NULL,
	EFF_DT      	DATE NOT NULL,
	EFF_DEL_FLAG	CHAR(1) NOT NULL,
	REV_DT      	DATE NOT NULL,
	REV_DEL_FLAG	CHAR(1) NOT NULL,
	CONSTRAINT PK_SUB_ISSUE_FUNDAMENTAL_DATA PRIMARY KEY(SUB_ISSUE_ID,ITEM_CODE_ID,DT,EFF_DT,REV_DT)
	NOT DEFERRABLE
	 VALIDATE
)

ALTER TABLE MODELDB_GLOBAL.SUB_ISSUE_FUNDAMENTAL_DATA
	ADD ( CONSTRAINT CON_AD_FUNDAMENTAL_DATA_REV
	CHECK (rev_del_flag IN ('Y', 'N'))
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )

ALTER TABLE MODELDB_GLOBAL.SUB_ISSUE_FUNDAMENTAL_DATA
	ADD ( CONSTRAINT CON_AD_FUNDAMENTAL_DATA_EFF
	CHECK (eff_del_flag IN ('Y', 'N'))
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )

DROP VIEW SUB_ISSUE_FUNDAMENTAL_DATA_ACT
CREATE VIEW MODELDB_GLOBAL.SUB_ISSUE_FUNDAMENTAL_DATA_ACT ( SUB_ISSUE_ID, ITEM_CODE_ID, DT, VALUE, CURRENCY_ID, FISCAL_YEAR_END, EFF_DT, EFF_DEL_FLAG )
BEQUEATH DEFINER AS
(
  SELECT sub_issue_id, item_code_id, dt, value, currency_id, fiscal_year_END, eff_dt, eff_del_flag
  FROM SUB_ISSUE_FUNDAMENTAL_DATA t1
  WHERE rev_dt=(SELECT MAX(rev_dt) FROM SUB_ISSUE_FUNDAMENTAL_DATA t2
    WHERE t1.sub_issue_id = t2.sub_issue_id AND t1.item_code_id = t2.item_code_id
    AND t1.dt = t2.dt AND t1.eff_dt = t2.eff_dt)
  AND rev_del_flag='N')

