DROP TABLE rms_factor_statistics CASCADE CONSTRAINTS;
CREATE TABLE rms_factor_statistics
(
	rms_id		INT NOT NULL,
	dt		DATE NOT NULL,
	sub_factor_id	INT NOT NULL,
	std_error	NUMBER,
	t_value		NUMBER,
	t_probability	NUMBER,
	regr_constraint_weight	NUMBER,
	PRIMARY KEY (rms_id, dt, sub_factor_id)
) NOLOGGING
  TABLESPACE gmdl_rms_main;

DROP TABLE rms_factor_statistics_internal CASCADE CONSTRAINTS;
CREATE TABLE MODELDB_GLOBAL.RMS_FACTOR_STATISTICS_INTERNAL ( 
    RMS_ID                	NUMBER(38,0) NOT NULL,
    DT                    	DATE NOT NULL,
    SUB_FACTOR_ID         	NUMBER(38,0) NOT NULL,
    STD_ERROR             	NUMBER NULL,
    T_VALUE               	NUMBER NULL,
    T_PROBABILITY         	NUMBER NULL,
    REGR_CONSTRAINT_WEIGHT	NUMBER NULL,
    PRIMARY KEY(RMS_ID,DT,SUB_FACTOR_ID)
	NOT DEFERRABLE
USING INDEX 
TABLESPACE GMDL_RMS_MAIN PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 )
NOLOGGING 
)
TABLESPACE GMDL_RMS_MAIN NOCOMPRESS PCTFREE 10 INITRANS 1 MAXTRANS 255 
STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 )
PARALLEL( DEGREE 1 )
NOLOGGING 
NOCACHE 
MONITORING 
NOROWDEPENDENCIES
DISABLE ROW MOVEMENT 
GO
