CREATE TABLE
    EXCHANGE_ATTRIBUTE
    (
        CLASSIFICATION_REF_ID NUMBER(38) NOT NULL,
        MIC_CODE NVARCHAR2(10),
        PRIMARY KEY (CLASSIFICATION_REF_ID)
    );
COMMENT ON TABLE EXCHANGE_ATTRIBUTE
IS
    'Maps an exchange to it''s MIC code';
COMMENT ON COLUMN EXCHANGE_ATTRIBUTE.CLASSIFICATION_REF_ID
IS
    'References MARKETDB_GLOBAL.CLASSIFICATION_REF.ID';
COMMENT ON COLUMN EXCHANGE_ATTRIBUTE.MIC_CODE
IS
    'See ISO 10383 (http://www.iso15022.org/MIC/homepageMIC.htm)';