CREATE TABLE MODELDB_VITAL.RMG_CURRENCY_BETA  ( 
    DT              DATE NOT NULL,
    SUB_ISSUE_ID    CHAR(12) NOT NULL,
    RMG_ID          NUMBER(38) NOT NULL,
    ISO             VARCHAR2(3) NOT NULL,
    ASSET_TYPE      CHAR(12) NULL,
    MARKET          CHAR(12) NULL,
    VALUE           NUMBER NULL,
    P_VALUE         NUMBER NULL,
    NOBS            NUMBER(6) NULL,
    CONSTRAINT PK_RMG_CURRENCY_BETA PRIMARY KEY(DT,SUB_ISSUE_ID,RMG_ID,ISO)
    NOT DEFERRABLE
USING INDEX 
TABLESPACE GMDL_META PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT )
LOGGING 
)
TABLESPACE GMDL_META NOCOMPRESS PCTFREE 10 INITRANS 1 MAXTRANS 255 
STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT )
NOPARALLEL
LOGGING 
NOCACHE 
MONITORING 
NOROWDEPENDENCIES
DISABLE ROW MOVEMENT 
GO
CREATE INDEX MODELDB_VITAL.IDX_RMGCURRBETA_SUBISSUEID
    ON MODELDB_VITAL.RMG_CURRENCY_BETA(SUB_ISSUE_ID)
TABLESPACE GMDL_META NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT )
VISIBLE
NOPARALLEL
LOGGING 
GO

