DROP TABLE rms_factor_return CASCADE CONSTRAINTS;
CREATE TABLE rms_factor_return
(
	rms_id		INT NOT NULL,
	sub_factor_id	INT NOT NULL,
	dt		DATE NOT NULL,
	value		NUMBER NOT NULL,
	cumulative	NUMBER,
	PRIMARY KEY (rms_id, dt, sub_factor_id)
) ORGANIZATION INDEX
  NOLOGGING
  TABLESPACE gmdl_rms_returns;

CREATE TABLE MODELDB_GLOBAL.RMS_FACTOR_RETURN_INTERNAL ( 
    RMS_ID       	NUMBER(38,0) NOT NULL,
    SUB_FACTOR_ID	NUMBER(38,0) NOT NULL,
    DT           	DATE NOT NULL,
    VALUE        	NUMBER NOT NULL,
    PRIMARY KEY(RMS_ID,DT,SUB_FACTOR_ID)
	NOT DEFERRABLE
        USING INDEX 
)
ORGANIZATION INDEX
NOLOGGING TABLESPACE GMDL_RMS_RETURNS;