CREATE TABLE MODELDB_GLOBAL.RMG_PROXY_RETURN  ( 
    DT              DATE NOT NULL,
    SUB_ISSUE_ID    CHAR(12) NOT NULL,
    VALUE           NUMBER NULL,
    CONSTRAINT PK_RMG_PROXY_RETURN PRIMARY KEY(DT,SUB_ISSUE_ID)
    NOT DEFERRABLE
     VALIDATE
)
GO

CREATE TABLE MODELDB_GLOBAL.RMG_ISC_SCORE  ( 
    DT              DATE NOT NULL,
    SUB_ISSUE_ID    CHAR(12) NOT NULL,
    VALUE           NUMBER NULL,
    CONSTRAINT PK_RMG_ISC_DISTANCE PRIMARY KEY(DT,SUB_ISSUE_ID)
    NOT DEFERRABLE
     VALIDATE
)
GO

CREATE TABLE MODELDB_GLOBAL.RMS_STND_MEAN  ( 
    RMS_ID          NUMBER(38) NOT NULL,
    SUB_FACTOR_ID   NUMBER(38) NOT NULL,
    DT              DATE NOT NULL,
    VALUE           NUMBER NOT NULL,
    PRIMARY KEY(RMS_ID,DT,SUB_FACTOR_ID)
    NOT DEFERRABLE
     VALIDATE
)
GO

CREATE TABLE MODELDB_GLOBAL.RMS_STND_STDEV  ( 
    RMS_ID          NUMBER(38) NOT NULL,
    SUB_FACTOR_ID   NUMBER(38) NOT NULL,
    DT              DATE NOT NULL,
    VALUE           NUMBER NOT NULL,
    PRIMARY KEY(RMS_ID,DT,SUB_FACTOR_ID)
    NOT DEFERRABLE
     VALIDATE
)
GO

CREATE TABLE MODELDB_GLOBAL.RMG_ISC_PVALUE  (
    DT              DATE NOT NULL,
    SUB_ISSUE1_ID   CHAR(12) NOT NULL,
    SUB_ISSUE2_ID   CHAR(12) NOT NULL,
    VALUE           NUMBER NULL,
    PRIMARY KEY(DT,SUB_ISSUE1_ID,SUB_ISSUE2_ID)
    NOT DEFERRABLE
     VALIDATE
)
GO

CREATE TABLE MODELDB_GLOBAL.RMG_ISC_BETA  (
    DT              DATE NOT NULL,
    SUB_ISSUE1_ID   CHAR(12) NOT NULL,
    SUB_ISSUE2_ID   CHAR(12) NOT NULL,
    VALUE           NUMBER NULL,
    PRIMARY KEY(DT,SUB_ISSUE1_ID,SUB_ISSUE2_ID)
    NOT DEFERRABLE
     VALIDATE
)
GO


CREATE TABLE MODELDB_GLOBAL.RMG_HISTORIC_BETA_V3  ( 
    DT              DATE NOT NULL,
    SUB_ISSUE_ID    CHAR(12) NOT NULL,
    HOME            INTEGER NOT NULL,
    VALUE           NUMBER NULL,
    ROBUST_VALUE    NUMBER NULL,
    P_VALUE         NUMBER NULL,
    NOBS            NUMBER (6) NULL,
    CONSTRAINT PK_RMG_HISTORIC_BETA_V3 PRIMARY KEY(DT,SUB_ISSUE_ID, HOME)
    NOT DEFERRABLE
     VALIDATE
)
GO

CREATE TABLE MODELDB_GLOBAL.RMG_MARKET_RETURN_V3  ( 
    DT      DATE NOT NULL,
    RMG_ID  NUMBER(38) NOT NULL,
    VALUE   NUMBER NULL,
    PRIMARY KEY(DT,RMG_ID)
    NOT DEFERRABLE
     VALIDATE
)
GO
ALTER TABLE MODELDB_GLOBAL.RMG_MARKET_RETURN_V3
    ADD ( CONSTRAINT FK_RMG_MARKET_RETURN_V3
    FOREIGN KEY(RMG_ID)
    REFERENCES MODELDB_GLOBAL.RISK_MODEL_GROUP(RMG_ID)
    NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
GO

CREATE TABLE MODELDB_GLOBAL.RMI_PREDICTED_BETA_V3  (
    RMS_ID          NUMBER(38) NOT NULL,
    DT              DATE NOT NULL,
    SUB_ISSUE_ID    CHAR(12) NOT NULL,
    SHRINKAGE       NUMBER NULL,
    STYLE_SHRINK    NUMBER NULL,
    MISSPEC         NUMBER NULL,
    LOCAL_BETA      NUMBER NULL,
    LOCAL_NUM_BETA  NUMBER NULL,
    GLOBAL_BETA     NUMBER NULL,
    CONSTRAINT PK_RMI_PREDICTED_BETA_V3 PRIMARY KEY(RMS_ID,DT,SUB_ISSUE_ID)
    NOT DEFERRABLE
     VALIDATE
) ORGANIZATION INDEX
  NOLOGGING
  PARTITION BY LIST (rms_id)
(
        PARTITION p_predbeta_r12 VALUES (12) TABLESPACE gmdl_rms_main_r12,
        PARTITION p_predbeta_r17 VALUES (17) TABLESPACE gmdl_rms_main_r17,
        PARTITION p_predbeta_r20 VALUES (20) TABLESPACE gmdl_rms_main_r20,
        PARTITION p_predbeta_r21 VALUES (21) TABLESPACE gmdl_rms_main_r21,
        PARTITION p_predbeta_r22 VALUES (22) TABLESPACE gmdl_rms_main_r22,
        PARTITION p_predbeta_r83 VALUES (83) TABLESPACE gmdl_rms_main_r83,
        PARTITION p_predbeta_r84 VALUES (84) TABLESPACE gmdl_rms_main_r84,
        PARTITION p_predbeta_r87 VALUES (87) TABLESPACE gmdl_rms_main_r87,
        PARTITION p_predbeta_r88 VALUES (88) TABLESPACE gmdl_rms_main_r88,
        PARTITION p_predbeta_r109 VALUES (109) TABLESPACE gmdl_rms_main_r109,
        PARTITION p_predbeta_r110 VALUES (110) TABLESPACE gmdl_rms_main_r110,
        PARTITION p_predbeta_r113 VALUES (113) TABLESPACE gmdl_rms_main_r113,
        PARTITION p_predbeta_r114 VALUES (114) TABLESPACE gmdl_rms_main_r114,
        PARTITION p_predbeta_r131 VALUES (131) TABLESPACE gmdl_rms_main_r131,
        PARTITION p_predbeta_r132 VALUES (132) TABLESPACE gmdl_rms_main_r132,
        PARTITION p_predbeta_r133 VALUES (133) TABLESPACE gmdl_rms_main_r133,
        PARTITION p_predbeta_r134 VALUES (134) TABLESPACE gmdl_rms_main_r134,
        PARTITION p_predbeta_r170 VALUES (170) TABLESPACE gmdl_rms_main_r170,
        PARTITION p_predbeta_r171 VALUES (171) TABLESPACE gmdl_rms_main_r171,
        PARTITION p_predbeta_r172 VALUES (172) TABLESPACE gmdl_rms_main_r172,
        PARTITION p_predbeta_r173 VALUES (173) TABLESPACE gmdl_rms_main_r173,
        PARTITION p_predbeta_catchall VALUES (DEFAULT) TABLESPACE gmdl_rms_main
)
GO

CREATE TABLE MODELDB_GLOBAL.RMI_ESTU_NESTED_INFO
(
     RMS_ID NUMBER(38) NOT NULL,
      ID NUMBER(6) NOT NULL,
      NAME VARCHAR(30) NOT NULL,
     PRIMARY KEY (RMS_ID,ID)
)
GO

CREATE TABLE MODELDB_GLOBAL.RMI_ESTU_V3
(
    RMS_ID NUMBER(38) NOT NULL,
    NESTED_ID NUMBER(6) NOT NULL,
    DT DATE NOT NULL,
    SUB_ISSUE_ID CHAR(12) NOT NULL,
    QUALIFY NUMBER(38),
    WEIGHT NUMBER(15,5),
    PRIMARY KEY (RMS_ID, DT, NESTED_ID, SUB_ISSUE_ID)
) ORGANIZATION INDEX
  NOLOGGING
  PARTITION BY LIST (rms_id)
(
        PARTITION p_estu_r170 VALUES (170) TABLESPACE gmdl_rms_main_r170,
        PARTITION p_estu_r171 VALUES (171) TABLESPACE gmdl_rms_main_r171,
        PARTITION p_estu_r172 VALUES (172) TABLESPACE gmdl_rms_main_r172,
        PARTITION p_estu_r173 VALUES (173) TABLESPACE gmdl_rms_main_r173,
        PARTITION p_estu_catchall VALUES (DEFAULT) TABLESPACE gmdl_rms_main
)
GO

CREATE TABLE MODELDB_GLOBAL.RMS_STATISTICAL_FACTOR_RETURN  ( 
    RMS_ID          NUMBER(38) NOT NULL,
    SUB_FACTOR_ID   NUMBER(38) NOT NULL,
    EXP_DT          DATE NOT NULL,
    DT              DATE NOT NULL,
    VALUE           NUMBER NOT NULL,
    CUMULATIVE      NUMBER NULL,
    PRIMARY KEY(RMS_ID,EXP_DT,DT,SUB_FACTOR_ID)
    NOT DEFERRABLE
     VALIDATE
)
GO

CREATE TABLE MODELDB_GLOBAL.RMG_REGION_MAP  (
    ID          NUMBER (38) NOT NULL,
    RMG_ID      NUMBER (38) NOT NULL,
    FROM_DT     DATE NOT NULL,
    THRU_DT     DATE NOT NULL,
    PRIMARY KEY(ID,RMG_ID,FROM_DT)
    NOT DEFERRABLE
    VALIDATE
)
GO


CREATE TABLE MODELDB_GLOBAL.REGION_RETURN  (
    DT      DATE NOT NULL,
    ID      NUMBER(38) NOT NULL,
    VALUE   NUMBER NULL,
    PRIMARY KEY(DT,ID)
    NOT DEFERRABLE
    VALIDATE
)
GO

CREATE TABLE MODELDB_GLOBAL.RMS_STND_STATS  (
    RMS_ID          NUMBER(38) NOT NULL,
    DESCRIPTOR_ID   NUMBER(38) NOT NULL,
    DT              DATE NOT NULL,
    MEAN            NUMBER,
    STDEV           NUMBER,
    PRIMARY KEY(RMS_ID,DT,DESCRIPTOR_ID)
    NOT DEFERRABLE
     VALIDATE
)
GO

CREATE TABLE MODELDB_GLOBAL.RMS_FACTOR_RETURN_INTERNAL  ( 
    RMS_ID          NUMBER(38) NOT NULL,
    SUB_FACTOR_ID   NUMBER(38) NOT NULL,
    DT              DATE NOT NULL,
    VALUE           NUMBER NOT NULL,
    PRIMARY KEY(RMS_ID,DT,SUB_FACTOR_ID)
    NOT DEFERRABLE
     VALIDATE
)
GO

CREATE TABLE MODELDB_GLOBAL.RMS_ROBUST_WEIGHT_INTERNAL  ( 
    RMS_ID          NUMBER(38) NOT NULL,
    SUB_ISSUE_ID    CHAR(12) NOT NULL,
    DT              DATE NOT NULL,
    REG_ID          NUMBER(38) NOT NULL,
    VALUE           NUMBER NULL, 
    PRIMARY KEY(RMS_ID,DT,REG_ID,SUB_ISSUE_ID)
    NOT DEFERRABLE
USING INDEX 
TABLESPACE GMDL_RMS_MAIN PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT )
NOLOGGING 
)
TABLESPACE GMDL_RMS_MAIN NOCOMPRESS PCTFREE 10 INITRANS 1 MAXTRANS 255 
STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT )
NOPARALLEL
NOLOGGING 
NOCACHE 
MONITORING 
NOROWDEPENDENCIES
DISABLE ROW MOVEMENT 
    PARTITION BY LIST (RMS_ID)
    (   PARTITION P_ROBWTINT_RM13 VALUES (-13),
        PARTITION P_ROBWTINT_CATCHALL VALUES (DEFAULT))
GO

CREATE TABLE MODELDB_GLOBAL.RMG_RETURNS_TIMING_ADJ  ( 
    TIMING_ID   NUMBER(38) NOT NULL,
    RMG_ID      NUMBER(38) NOT NULL,
    DT          DATE NOT NULL,
    VALUE       NUMBER NOT NULL,
    PROXY       NUMBER NOT NULL,
    PRIMARY KEY(TIMING_ID,DT,RMG_ID)
    NOT DEFERRABLE
     VALIDATE
)
GO
