CREATE TABLE
    RMI_NESTU
    (
        RMS_ID NUMBER(38) NOT NULL,
        DT DATE NOT NULL,
        SUB_ISSUE_ID CHAR(12) NOT NULL,
        NEST_ID NUMBER(10) NOT NULL,
        WEIGHT BINARY_DOUBLE,
        PRIMARY KEY (RMS_ID, DT, SUB_ISSUE_ID, NEST_ID),
        FOREIGN KEY (RMS_ID) REFERENCES RISK_MODEL_SERIE (SERIAL_ID),
        FOREIGN KEY (NEST_ID) REFERENCES NEST (ID)
    );
COMMENT ON TABLE RMI_NESTU
IS
    'Estimation universe for each nested regression';