
AXIOMA_FACTOR_NAMES = [
['Value (2_1)', 'Earnings-to-Price and Book-to-Price', 'Value'],
['Book-to-Price', 'Annualized Book-to-Price', 'Value'],
['Earnings-to-Price', 'Annualized Earnings-to-Price', 'Value'],
['Sales-to-Price', 'Annualized Sales-to-Price', 'Value'],
['Est Earnings-to-Price', 'Earnings-to-Price and Forecast Earnings-to-Price', 'Value'],
['Dividend Payout', 'Annualized DPS/EPS', 'Cash Policy'],
['Proxied Dividend Payout', 'Annualized DPS / Income', 'Cash Policy'],
['Growth (2_1)', 'ROE*Plowback + 5-year earnings growth + 5-year sales growth', 'Growth'],
['Sustainable Growth Rate', 'ROE*Plowback', 'Growth'],
['Sales Growth', '5-year Sales Growth', 'Growth'],
['Est Sales Growth', '5-year Sales inc. Forecast Sales. Slope of regression line.', 'Growth'],
['Earnings Growth', '5-year Earnings Growth', 'Growth'],
['Est Earnings Growth', '5-year Earnings  inc. Forecast Earnings. Slope of regression line.', 'Growth'],
['Debt-to-MarketCap', 'Ratio of total debt to Market Cap', 'Leverage'],
['Return-on-Assets', 'Ratio of annualized  income to total assets', 'Quality'],
['Liquidity (2_1)', 'Ratio of 21-day trading volume to market cap', 'Liquidity'],
['Dollar Volume', '21-day trading volume', 'Liquidity'],
['Amihud Liquidity', 'Log of market-cap adjusted Amihud liquidity measure', 'Liquidity'],
['Volatility 60 Day', '60-day Volatility', 'Volatility'],
['Volatility 250 Day', '250-day Volatility', 'Volatility'],
['Volatility 250 Day (PartOg)', '250-day Volatility', 'Volatility'],
['Volatility 125 Day', '125-day Volatility', 'Volatility'],
['Historical Residual Volatility', '250-day Historical Volatility of residual asset returns', 'Volatility'],
['Market Sensitivity SH (PartOg)', '125-day Beta of Asset Return relative to Market Return', 'Volatility'],
['Market Sensitivity (PartOg)', '250-day Beta of Asset Return relative to Market Return', 'Volatility'],
['Medium-Term Momentum (6 Months)', 'Momentum of T-20 to T-120 day returns', 'Momentum'],
['Yearly Momentum', 'Momentum of last 250-day returns', 'Momentum'],
['Exchange Rate Sensitivity (GBP)', '52-week beta of asset returns vs. market + GBP return', 'Exchange Rate Sensitivity'],
['Exchange Rate Sensitivity (EUR)', '52-week beta of asset returns vs. market + EUR return', 'Exchange Rate Sensitivity'],
['Exchange Rate Sensitivity (JPY)', '52-week beta of asset returns vs. market + JPY return', 'Exchange Rate Sensitivity'],
]


TRANSLATED_AXIOMA_FACTOR_NAMES={
'Medium-Term Momentum (6 Months)':'6 Month Momentum'
}

AXIOMA_WW_FACTOR_NAMES = [
['Amihud Liquidity 60 Day','Amihud Liquidity 60 Day','Liquidity'],
['Amihud Liquidity 125 Day','Amihud Liquidity 125 Day','Liquidity'],
['Book to Price Annual','Book to Price Annual','Value'],
['Cash Flow to Assets Annual','Cash Flow to Assets Annual','Profitability'],
['Cash Flow to Income Annual','Cash Flow to Income Annual','Profitability'],
['Debt to Assets Annual','Debt to Assets Annual','Leverage'],
['Debt to Equity Annual','Debt to Equity Annual','Leverage'],
['Dividend Yield Annual','Dividend Yield Annual','Cash Policy'],
['Earnings to Price Annual','Earnings to Price Annual','Value'],
['Est Earnings to Price Annual','Est Earnings to Price Annual','Value'],
['Earnings Growth Annual','5 Year Earnings Growth','Growth'],
['Gross Margin Annual','Gross Margin Annual','Profitability'],
['Returns to Trading Days','Returns to Trading Days','Liquidity'],
['Log of Issuer Cap','Log of Issuer Cap','Size'],
['Log of 20-Day ADV to Issuer Cap','Log of 20-Day ADV to Issuer Cap','Liquidity'],
['Log of 60-Day ADV to Issuer Cap','Log of 60-Day ADV to Issuer Cap','Liquidity'],
['Annual Return Excl Prev Month','Annual Return Excl Prev Month','Momentum'],
['Monthly Return','Monthly Return','Momentum'],
['Regional Market Sensitivity 250 Day','Regional Market Sensitivity 250 Day','Volatility'],
['Regional Market Sensitivity 500 Day','Regional Market Sensitivity 500 Day','Volatility'],
['Return on Assets Annual','Return on Assets Annual','Profitability'],
['Return on Equity Annual','Return on Equity Annual','Profitability'],
['Sales to Assets Annual','Sales to Assets Annual','Profitability'],
['Sales Growth Annual','5 Year Sales Growth','Growth'],
['Volatility 60 Day','Volatility 60 Day','Volatility'],
['Volatility 125 Day','Volatility 125 Day','Volatility'],
['Exchange Rate Sensitivity 52 Week XDR','Exchange Rate Sensitivity 52 Week XDR','Exchange Rate Sensitivity'],
['Exchange Rate Sensitivity 104 Week XDR','Exchange Rate Sensitivity 104 Week XDR','Exchange Rate Sensitivity'],
]

TRANSLATED_AXIOMA_WW_FACTOR_NAMES={
}

AXIOMA_US4_FACTOR_NAMES = [
['Book to Price Quarterly', 'Book to Price Quarterly', 'Value'],
['Earnings to Price Quarterly', 'Earnings to Price Quarterly', 'Value'],
['Est Earnings to Price Quarterly', 'Est Earnings to Price Quarterly', 'Value'],
['Debt to Assets Quarterly', 'Debt to Assets Quarterly', 'Leverage'],
['Debt to Equity Quarterly', 'Debt to Equity Quarterly', 'Leverage'],
['Earnings Growth Quarterly', 'Earnings Growth Quarterly', 'Growth'],
['Sales Growth Quarterly', 'Sales Growth Quarterly', 'Growth'],
['Dividend Yield Quarterly', 'Dividend Yield Quarterly', 'Cash Policy'],
['Log of Issuer Cap', 'Log of Issuer Cap', 'Size'],
['Log of 20-Day ADV to Issuer Cap', 'Log of 20-Day ADV to Issuer Cap', 'Liquidity'],
['Log of 60-Day ADV to Issuer Cap', 'Log of 60-Day ADV to Issuer Cap', 'Liquidity'],
['Market Sensitivity 125 Day', 'Market Sensitivity 125 Day', 'Volatility'],
['Market Sensitivity 250 Day', 'Market Sensitivity 250 Day', 'Volatility'],
['Volatility 60 Day', 'Volatility 60 Day', 'Volatility'],
['Volatility 125 Day', 'Volatility 125 Day', 'Volatility'],
['Annual Return Excl Prev Month', 'Annual Return Excl Prev Month', 'Momentum'],
['Monthly Return', 'Monthly Return', 'Momentum'],
['Exchange Rate Sensitivity 52 Week XDR', 'Exchange Rate Sensitivity 52 Week XDR', 'Exchange Rate Sensitivity'],
['Exchange Rate Sensitivity 104 Week XDR', 'Exchange Rate Sensitivity 104 Week XDR', 'Exchange Rate Sensitivity'],
['Return on Equity Quarterly', 'Return on Equity Quarterly', 'Profitability'],
['Return on Assets Quarterly', 'Return on Assets Quarterly', 'Profitability'],
['Cash Flow to Assets Annual', 'Cash Flow to Assets Annual', 'Profitability'],
['Cash Flow to Income Annual', 'Cash Flow to Income Annual', 'Profitability'],
['Sales to Assets Quarterly', 'Sales to Assets Quarterly', 'Profitability'],
['Gross Margin Quarterly', 'Gross Margin Quarterly', 'Profitability'],
]

TRANSLATED_AXIOMA_US4_FACTOR_NAMES = {
}

AXIOMA_EU4_FACTOR_NAMES = [
['Amihud Liquidity 60 Day','Amihud Liquidity 60 Day','Liquidity'],
['Amihud Liquidity 125 Day','Amihud Liquidity 125 Day','Liquidity'],
['Book to Price Annual','Book to Price Annual','Value'],
['Cash Flow to Assets Annual','Cash Flow to Assets Annual','Profitability'],
['Cash Flow to Income Annual','Cash Flow to Income Annual','Profitability'],
['Debt to Assets Annual','Debt to Assets Annual','Leverage'],
['Debt to Equity Annual','Debt to Equity Annual','Leverage'],
['Dividend Yield Annual','Dividend Yield Annual','Cash Policy'],
['Earnings to Price Annual','Earnings to Price Annual','Value'],
['Est Earnings to Price Annual','Est Earnings to Price Annual','Value'],
['Earnings Growth Annual','5 Year Earnings Growth','Growth'],
['Gross Margin Annual','Gross Margin Annual','Profitability'],
['Returns to Trading Days','Returns to Trading Days','Liquidity'],
['Log of Issuer Cap','Log of Issuer Cap','Size'],
['Log of 20-Day ADV to Issuer Cap','Log of 20-Day ADV to Issuer Cap','Liquidity'],
['Log of 60-Day ADV to Issuer Cap','Log of 60-Day ADV to Issuer Cap','Liquidity'],
['Annual Return Excl Prev Month','Annual Return Excl Prev Month','Momentum'],
['Monthly Return','Monthly Return','Momentum'],
['Europe Regional Market Sensitivity 250 Day','Regional Market Sensitivity 250 Day','Volatility'],
['Europe Regional Market Sensitivity 500 Day','Regional Market Sensitivity 500 Day','Volatility'],
['Return on Assets Annual','Return on Assets Annual','Profitability'],
['Return on Equity Annual','Return on Equity Annual','Profitability'],
['Sales to Assets Annual','Sales to Assets Annual','Profitability'],
['Sales Growth Annual','5 Year Sales Growth','Growth'],
['Volatility 60 Day','Volatility 60 Day','Volatility'],
['Volatility 125 Day','Volatility 125 Day','Volatility'],
['Exchange Rate Sensitivity 52 Week XDR','Exchange Rate Sensitivity 52 Week XDR','Exchange Rate Sensitivity'],
['Exchange Rate Sensitivity 104 Week XDR','Exchange Rate Sensitivity 104 Week XDR','Exchange Rate Sensitivity'],
]

TRANSLATED_AXIOMA_EU4_FACTOR_NAMES={
}

AXIOMA_WWEL_FACTOR_NAMES = [
['US 10Y Interest Rate Sensitivity 104W (net of market)', '104-week beta: asset returns vs market returns and 10Y US Treasuries yield movements', 'Interest Rate Sensitivity'],
['US 10Y Interest Rate Sensitivity 104W', '104-week beta: asset returns vs 10Y US Treasuries yield movements', 'Interest Rate Sensitivity'],
['US 6M Interest Rate Sensitivity 104W (net of market)', '104-week beta: asset returns vs market returns and 6M US Treasuries yield movements', 'Interest Rate Sensitivity'],
['US 6M Interest Rate Sensitivity 104W', '104-week beta: asset returns vs 6M US Treasuries yield movements', 'Interest Rate Sensitivity'],
['US Term Spread Sensitivity 104W (net of market)', '104-week beta: asset returns vs market returns and 10Y-6M US Treasuries spread movements', 'Interest Rate Sensitivity'],
['US Term Spread Sensitivity 104W', '104-week beta: asset returns vs 10Y-6M US Treasuries spread movements', 'Interest Rate Sensitivity'],
['US Credit Spread Sensitivity 104W (net of market)', '104-week beta: asset returns vs market returns and BBB US corporate bond spread movements', 'Interest Rate Sensitivity'],
['US Credit Spread Sensitivity 104W', '104-week beta: asset returns vs BBB US corporate bond spread movements', 'Interest Rate Sensitivity'],
['Oil Sensitivity 104W (net of market)', '104-week beta: asset returns vs market returns and crude oil WTI returns', 'Commodity Sensitivity'],
['Oil Sensitivity 104W', '104-week beta: asset returns vs crude oil WTI returns', 'Commodity Sensitivity'],
['Gold Sensitivity 104W (net of market)', '104-week beta: asset returns vs market returns and GSCI Gold spot price returns', 'Commodity Sensitivity'],
['Gold Sensitivity 104W', '104-week beta: asset returns vs GSCI Gold spot price returns', 'Commodity Sensitivity'],
['Commodity Sensitivity 104W (net of market)', '104-week beta: asset returns vs market returns and GSCI Non-energy spot price returns', 'Commodity Sensitivity'],
['Commodity Sensitivity 104W', '104-week beta: asset returns vs GSCI Non-energy spot price returns', 'Commodity Sensitivity'],
['US BEI Sensitivity 104W (net of market)', '104-week beta: asset returns vs market returns and US break-even inflation rate movements', 'Inflation Rate Sensitivity'],
['US BEI Sensitivity 104W', '104-week beta: asset returns vs US break-even inflation rate movements', 'Inflation Rate Sensitivity'],
['GB 10Y Interest Rate Sensitivity 104W (net of market)', '104-week beta: asset returns vs market returns and 10Y GB Treasuries yield movements', 'Interest Rate Sensitivity'],
['GB 10Y Interest Rate Sensitivity 104W', '104-week beta: asset returns vs 10Y GB Treasuries yield movements', 'Interest Rate Sensitivity'],
['JP 10Y Interest Rate Sensitivity 104W (net of market)', '104-week beta: asset returns vs market returns and 10Y JP Treasuries yield movements', 'Interest Rate Sensitivity'],
['JP 10Y Interest Rate Sensitivity 104W', '104-week beta: asset returns vs 10Y JP Treasuries yield movements', 'Interest Rate Sensitivity'],
['EU 10Y Interest Rate Sensitivity 104W (net of market)', '104-week beta: asset returns vs market returns and 10Y EU Treasuries yield movements', 'Interest Rate Sensitivity'],
['EU 10Y Interest Rate Sensitivity 104W', '104-week beta: asset returns vs 10Y EU Treasuries yield movements', 'Interest Rate Sensitivity'],
['GB 6M Interest Rate Sensitivity 104W (net of market)', '104-week beta: asset returns vs market returns and 6M GB Treasuries yield movements', 'Interest Rate Sensitivity'],
['GB 6M Interest Rate Sensitivity 104W', '104-week beta: asset returns vs 6M GB Treasuries yield movements', 'Interest Rate Sensitivity'],
['JP 6M Interest Rate Sensitivity 104W (net of market)', '104-week beta: asset returns vs market returns and 6M JP Treasuries yield movements', 'Interest Rate Sensitivity'],
['JP 6M Interest Rate Sensitivity 104W', '104-week beta: asset returns vs 6M JP Treasuries yield movements', 'Interest Rate Sensitivity'],
['EU 6M Interest Rate Sensitivity 104W (net of market)', '104-week beta: asset returns vs market returns and 6M EU Treasuries yield movements', 'Interest Rate Sensitivity'],
['EU 6M Interest Rate Sensitivity 104W', '104-week beta: asset returns vs 6M EU Treasuries yield movements', 'Interest Rate Sensitivity'],
['GB Term Spread Sensitivity 104W (net of market)', '104-week beta: asset returns vs market returns and 10Y-6M GB Treasuries spread movements', 'Interest Rate Sensitivity'],
['GB Term Spread Sensitivity 104W', '104-week beta: asset returns vs 10Y-6M GB Treasuries spread movements', 'Interest Rate Sensitivity'],
['JP Term Spread Sensitivity 104W (net of market)', '104-week beta: asset returns vs market returns and 10Y-6M JP Treasuries spread movements', 'Interest Rate Sensitivity'],
['JP Term Spread Sensitivity 104W', '104-week beta: asset returns vs 10Y-6M JP Treasuries spread movements', 'Interest Rate Sensitivity'],
['EU Term Spread Sensitivity 104W (net of market)', '104-week beta: asset returns vs market returns and 10Y-6M EU Treasuries spread movements', 'Interest Rate Sensitivity'],
['EU Term Spread Sensitivity 104W', '104-week beta: asset returns vs 10Y-6M EU Treasuries spread movements', 'Interest Rate Sensitivity'],
['GB Credit Spread Sensitivity 104W (net of market)', '104-week beta: asset returns vs market returns and BBB GB corporate bond spread movements', 'Interest Rate Sensitivity'],
['GB Credit Spread Sensitivity 104W ', '104-week beta: asset returns vs BBB GB corporate bond spread movements', 'Interest Rate Sensitivity'],
['JP Credit Spread Sensitivity 104W (net of market)', '104-week beta: asset returns vs market returns and BBB JP corporate bond spread movements', 'Interest Rate Sensitivity'],
['JP Credit Spread Sensitivity 104W', '104-week beta: asset returns vs BBB JP corporate bond spread movements', 'Interest Rate Sensitivity'],
['EU Credit Spread Sensitivity 104W (net of market)', '104-week beta: asset returns vs market returns and BBB EU corporate bond spread movements', 'Interest Rate Sensitivity'],
['EU Credit Spread Sensitivity 104W', '104-week beta: asset returns vs BBB EU corporate bond spread movements', 'Interest Rate Sensitivity'],
#['US Credit Spread Sensitivity 36M (net of market)', '36-month beta: asset returns vs market returns and BBB US corporate bond spread movements', 'Interest Rate Sensitivity'],
#['US Credit Spread Sensitivity 36M', '36-month beta: asset returns vs BBB US corporate bond spread movements', 'Interest Rate Sensitivity'],
#['GB Credit Spread Sensitivity 36M (net of market)', '36-month beta: asset returns vs market returns and BBB GB corporate bond spread movements', 'Interest Rate Sensitivity'],
#['GB Credit Spread Sensitivity 36M', '36-month beta: asset returns vs BBB GB corporate bond spread movements', 'Interest Rate Sensitivity'],
#['JP Credit Spread Sensitivity 36M (net of market)', '36-month beta: asset returns vs market returns and BBB JP corporate bond spread movements', 'Interest Rate Sensitivity'],
#['JP Credit Spread Sensitivity 36M', '36-month beta: asset returns vs BBB JP corporate bond spread movements', 'Interest Rate Sensitivity'],
#['EU Credit Spread Sensitivity 36M (net of market)', '36-month beta: asset returns vs market returns and BBB EU corporate bond spread movements', 'Interest Rate Sensitivity'],
#['EU Credit Spread Sensitivity 36M', '36-month beta: asset returns vs BBB EU corporate bond spread movements', 'Interest Rate Sensitivity'],
]

TRANSLATED_AXIOMA_WWEL_FACTOR_NAMES = {
}

AXIOMA_EM4_FACTOR_NAMES = [
['Amihud Liquidity 60 Day','Amihud Liquidity 60 Day','Liquidity'],
['Amihud Liquidity 125 Day','Amihud Liquidity 125 Day','Liquidity'],
['Book to Price Annual','Book to Price Annual','Value'],
['Cash Flow to Assets Annual','Cash Flow to Assets Annual','Profitability'],
['Cash Flow to Income Annual','Cash Flow to Income Annual','Profitability'],
['Debt to Assets Annual','Debt to Assets Annual','Leverage'],
['Debt to Equity Annual','Debt to Equity Annual','Leverage'],
['Dividend Yield Annual','Dividend Yield Annual','Cash Policy'],
['Earnings to Price Annual','Earnings to Price Annual','Value'],
['Est Earnings to Price Annual','Est Earnings to Price Annual','Value'],
['Earnings Growth Annual','5 Year Earnings Growth','Growth'],
['Gross Margin Annual','Gross Margin Annual','Profitability'],
['Returns to Trading Days','Returns to Trading Days','Liquidity'],
['Log of Issuer Cap','Log of Issuer Cap','Size'],
['Log of 20-Day ADV to Issuer Cap','Log of 20-Day ADV to Issuer Cap','Liquidity'],
['Log of 60-Day ADV to Issuer Cap','Log of 60-Day ADV to Issuer Cap','Liquidity'],
['Annual Return Excl Prev Month','Annual Return Excl Prev Month','Momentum'],
['Monthly Return','Monthly Return','Momentum'],
['EM Regional Market Sensitivity 250 Day','EM Regional Market Sensitivity 250 Day','Volatility'],
['EM Regional Market Sensitivity 500 Day','EM Regional Market Sensitivity 500 Day','Volatility'],
['Return on Assets Annual','Return on Assets Annual','Profitability'],
['Return on Equity Annual','Return on Equity Annual','Profitability'],
['Sales to Assets Annual','Sales to Assets Annual','Profitability'],
['Sales Growth Annual','5 Year Sales Growth','Growth'],
['EM Volatility 60 Day','EM Volatility 60 Day','Volatility'],
['EM Volatility 125 Day','EM Volatility 125 Day','Volatility'],
['Exchange Rate Sensitivity 52 Week XDR','Exchange Rate Sensitivity 52 Week XDR','Exchange Rate Sensitivity'],
['Exchange Rate Sensitivity 104 Week XDR','Exchange Rate Sensitivity 104 Week XDR','Exchange Rate Sensitivity'],
]

TRANSLATED_AXIOMA_EM4_FACTOR_NAMES={
}

AXIOMA_AP4_FACTOR_NAMES = [
['Amihud Liquidity 60 Day','Amihud Liquidity 60 Day','Liquidity'],
['Amihud Liquidity 125 Day','Amihud Liquidity 125 Day','Liquidity'],
['Book to Price Annual','Book to Price Annual','Value'],
['Cash Flow to Assets Annual','Cash Flow to Assets Annual','Profitability'],
['Cash Flow to Income Annual','Cash Flow to Income Annual','Profitability'],
['Debt to Assets Annual','Debt to Assets Annual','Leverage'],
['Debt to Equity Annual','Debt to Equity Annual','Leverage'],
['Dividend Yield Annual','Dividend Yield Annual','Cash Policy'],
['Earnings to Price Annual','Earnings to Price Annual','Value'],
['Est Earnings to Price Annual','Est Earnings to Price Annual','Value'],
['Earnings Growth Annual','5 Year Earnings Growth','Growth'],
['Gross Margin Annual','Gross Margin Annual','Profitability'],
['Returns to Trading Days','Returns to Trading Days','Liquidity'],
['Log of Issuer Cap','Log of Issuer Cap','Size'],
['Log of 20-Day ADV to Issuer Cap','Log of 20-Day ADV to Issuer Cap','Liquidity'],
['Log of 60-Day ADV to Issuer Cap','Log of 60-Day ADV to Issuer Cap','Liquidity'],
['Annual Return Excl Prev Month','Annual Return Excl Prev Month','Momentum'],
['Monthly Return','Monthly Return','Momentum'],
['APAC Regional Market Sensitivity 250 Day','APAC Regional Market Sensitivity 250 Day','Volatility'],
['APAC Regional Market Sensitivity 500 Day','APAC Regional Market Sensitivity 500 Day','Volatility'],
['Return on Assets Annual','Return on Assets Annual','Profitability'],
['Return on Equity Annual','Return on Equity Annual','Profitability'],
['Sales to Assets Annual','Sales to Assets Annual','Profitability'],
['Sales Growth Annual','5 Year Sales Growth','Growth'],
['APAC Volatility 60 Day','APAC Volatility 60 Day','Volatility'],
['APAC Volatility 125 Day','APAC Volatility 125 Day','Volatility'],
['Exchange Rate Sensitivity 52 Week XDR','Exchange Rate Sensitivity 52 Week XDR','Exchange Rate Sensitivity'],
['Exchange Rate Sensitivity 104 Week XDR','Exchange Rate Sensitivity 104 Week XDR','Exchange Rate Sensitivity'],
]

TRANSLATED_AXIOMA_AP4_FACTOR_NAMES={
}

AXIOMA_APxJP4_FACTOR_NAMES = [
['Amihud Liquidity 60 Day','Amihud Liquidity 60 Day','Liquidity'],
['Amihud Liquidity 125 Day','Amihud Liquidity 125 Day','Liquidity'],
['Book to Price Annual','Book to Price Annual','Value'],
['Cash Flow to Assets Annual','Cash Flow to Assets Annual','Profitability'],
['Cash Flow to Income Annual','Cash Flow to Income Annual','Profitability'],
['Debt to Assets Annual','Debt to Assets Annual','Leverage'],
['Debt to Equity Annual','Debt to Equity Annual','Leverage'],
['Dividend Yield Annual','Dividend Yield Annual','Cash Policy'],
['Earnings to Price Annual','Earnings to Price Annual','Value'],
['Est Earnings to Price Annual','Est Earnings to Price Annual','Value'],
['Earnings Growth Annual','5 Year Earnings Growth','Growth'],
['Gross Margin Annual','Gross Margin Annual','Profitability'],
['Returns to Trading Days','Returns to Trading Days','Liquidity'],
['Log of Issuer Cap','Log of Issuer Cap','Size'],
['Log of 20-Day ADV to Issuer Cap','Log of 20-Day ADV to Issuer Cap','Liquidity'],
['Log of 60-Day ADV to Issuer Cap','Log of 60-Day ADV to Issuer Cap','Liquidity'],
['Annual Return Excl Prev Month','Annual Return Excl Prev Month','Momentum'],
['Monthly Return','Monthly Return','Momentum'],
['APxJP Regional Market Sensitivity 250 Day','APxJP Regional Market Sensitivity 250 Day','Volatility'],
['APxJP Regional Market Sensitivity 500 Day','APxJP Regional Market Sensitivity 500 Day','Volatility'],
['Return on Assets Annual','Return on Assets Annual','Profitability'],
['Return on Equity Annual','Return on Equity Annual','Profitability'],
['Sales to Assets Annual','Sales to Assets Annual','Profitability'],
['Sales Growth Annual','5 Year Sales Growth','Growth'],
['APxJP Volatility 60 Day','APxJP Volatility 60 Day','Volatility'],
['APxJP Volatility 125 Day','APxJP Volatility 125 Day','Volatility'],
['Exchange Rate Sensitivity 52 Week XDR','Exchange Rate Sensitivity 52 Week XDR','Exchange Rate Sensitivity'],
['Exchange Rate Sensitivity 104 Week XDR','Exchange Rate Sensitivity 104 Week XDR','Exchange Rate Sensitivity'],
]

TRANSLATED_AXIOMA_APxJP4_FACTOR_NAMES={
}

AXIOMA_CN4_FACTOR_NAMES = [
['Amihud Liquidity 60 Day','Amihud Liquidity 60 Day','Liquidity'],
['Amihud Liquidity 125 Day','Amihud Liquidity 125 Day','Liquidity'],
['Book to Price Annual','Book to Price Annual','Value'],
['Cash Flow to Assets Annual','Cash Flow to Assets Annual','Profitability'],
['Cash Flow to Income Annual','Cash Flow to Income Annual','Profitability'],
['Debt to Assets Annual','Debt to Assets Annual','Leverage'],
['Debt to Equity Annual','Debt to Equity Annual','Leverage'],
['Dividend Yield Annual','Dividend Yield Annual','Cash Policy'],
['Earnings to Price Annual','Earnings to Price Annual','Value'],
['Est Earnings to Price Annual','Est Earnings to Price Annual','Value'],
['Earnings Growth Annual','5 Year Earnings Growth','Growth'],
['Gross Margin Annual','Gross Margin Annual','Profitability'],
['Returns to Trading Days','Returns to Trading Days','Liquidity'],
['Log of Issuer Cap','Log of Issuer Cap','Size'],
['Log of 20-Day ADV to Issuer Cap','Log of 20-Day ADV to Issuer Cap','Liquidity'],
['Log of 60-Day ADV to Issuer Cap','Log of 60-Day ADV to Issuer Cap','Liquidity'],
['Annual Return Excl Prev Month','Annual Return Excl Prev Month','Momentum'],
['Monthly Return','Monthly Return','Momentum'],
['Domestic China Market Sensitivity 52 Week','Domestic China Market Sensitivity 52 Week','Volatility'],
['Domestic China Market Sensitivity 104 Week','Domestic China Market Sensitivity 104 Week','Volatility'],
['Return on Assets Annual','Return on Assets Annual','Profitability'],
['Return on Equity Annual','Return on Equity Annual','Profitability'],
['Sales to Assets Annual','Sales to Assets Annual','Profitability'],
['Sales Growth Annual','5 Year Sales Growth','Growth'],
['Domestic China Volatility 60 Day','Domestic China Volatility 60 Day','Volatility'],
['Domestic China Volatility 125 Day','Domestic China Volatility 125 Day','Volatility'],
['Exchange Rate Sensitivity 52 Week XDR','Exchange Rate Sensitivity 52 Week XDR','Exchange Rate Sensitivity'],
['Exchange Rate Sensitivity 104 Week XDR','Exchange Rate Sensitivity 104 Week XDR','Exchange Rate Sensitivity'],
]

TRANSLATED_AXIOMA_CN4_FACTOR_NAMES={
}

AXIOMA_UK4_FACTOR_NAMES = [
['Amihud Liquidity 60 Day','Amihud Liquidity 60 Day','Liquidity'],
['Amihud Liquidity 125 Day','Amihud Liquidity 125 Day','Liquidity'],
['Book to Price Annual','Book to Price Annual','Value'],
['Cash Flow to Assets Annual','Cash Flow to Assets Annual','Profitability'],
['Cash Flow to Income Annual','Cash Flow to Income Annual','Profitability'],
['Debt to Assets Annual','Debt to Assets Annual','Leverage'],
['Debt to Equity Annual','Debt to Equity Annual','Leverage'],
['Dividend Yield Annual','Dividend Yield Annual','Cash Policy'],
['Earnings to Price Annual','Earnings to Price Annual','Value'],
['Est Earnings to Price Annual','Est Earnings to Price Annual','Value'],
['Earnings Growth Annual','5 Year Earnings Growth','Growth'],
['Gross Margin Annual','Gross Margin Annual','Profitability'],
['Returns to Trading Days','Returns to Trading Days','Liquidity'],
['Log of Issuer Cap','Log of Issuer Cap','Size'],
['Log of 20-Day ADV to Issuer Cap','Log of 20-Day ADV to Issuer Cap','Liquidity'],
['Log of 60-Day ADV to Issuer Cap','Log of 60-Day ADV to Issuer Cap','Liquidity'],
['Annual Return Excl Prev Month','Annual Return Excl Prev Month','Momentum'],
['Monthly Return','Monthly Return','Momentum'],
['Market Sensitivity 250 Day','Market Sensitivity 250 Day','Volatility'],
['Market Sensitivity 500 Day','Market Sensitivity 500 Day','Volatility'],
['Return on Assets Annual','Return on Assets Annual','Profitability'],
['Return on Equity Annual','Return on Equity Annual','Profitability'],
['Sales to Assets Annual','Sales to Assets Annual','Profitability'],
['Sales Growth Annual','5 Year Sales Growth','Growth'],
['Volatility 60 Day','Volatility 60 Day','Volatility'],
['Volatility 125 Day','Volatility 125 Day','Volatility'],
['Exchange Rate Sensitivity 52 Week XDR','Exchange Rate Sensitivity 52 Week XDR','Exchange Rate Sensitivity'],
['Exchange Rate Sensitivity 104 Week XDR','Exchange Rate Sensitivity 104 Week XDR','Exchange Rate Sensitivity'],
]

TRANSLATED_AXIOMA_UK4_FACTOR_NAMES={
}

AXIOMA_CA4_FACTOR_NAMES = [
['Amihud Liquidity 60 Day', 'Amihud Liquidity 60 Day', 'Liquidity'],
['Amihud Liquidity 125 Day', 'Amihud Liquidity 125 Day', 'Liquidity'],
['Book to Price Quarterly', 'Book to Price Quarterly', 'Value'],
['Cash Flow to Assets Annual', 'Cash Flow to Assets Annual', 'Profitability'],
['Cash Flow to Income Annual', 'Cash Flow to Income Annual', 'Profitability'],
['Debt to Assets Quarterly', 'Debt to Assets Quarterly', 'Leverage'],
['Debt to Equity Quarterly', 'Debt to Equity Quarterly', 'Leverage'],
['Dividend Yield Quarterly', 'Dividend Yield Quarterly', 'Cash Policy'],
['Earnings to Price Quarterly', 'Earnings to Price Quarterly', 'Value'],
['Est Earnings to Price Quarterly', 'Est Earnings to Price Quarterly', 'Value'],
['Earnings Growth Quarterly', '5 Year Earnings Growth', 'Growth'],
['Gross Margin Quarterly', 'Gross Margin Quarterly', 'Profitability'],
['Returns to Trading Days', 'Returns to Trading Days', 'Liquidity'],
['Log of Issuer Cap', 'Log of Issuer Cap', 'Size'],
['Log of 20-Day ADV to Issuer Cap', 'Log of 20-Day ADV to Issuer Cap', 'Liquidity'],
['Log of 60-Day ADV to Issuer Cap', 'Log of 60-Day ADV to Issuer Cap', 'Liquidity'],
['Annual Return Excl Prev Month', 'Annual Return Excl Prev Month', 'Momentum'],
['Monthly Return', 'Monthly Return', 'Momentum'],
['Market Sensitivity 250 Day', 'Market Sensitivity 250 Day', 'Volatility'],
['Market Sensitivity 500 Day', 'Market Sensitivity 500 Day', 'Volatility'],
['Return on Assets Quarterly', 'Return on Assets Quarterly', 'Profitability'],
['Return on Equity Quarterly', 'Return on Equity Quarterly', 'Profitability'],
['Sales to Assets Quarterly', 'Sales to Assets Quarterly', 'Profitability'],
['Sales Growth Quarterly', '5 Year Sales Growth', 'Growth'],
['Volatility 60 Day', 'Volatility 60 Day', 'Volatility'],
['Volatility 125 Day', 'Volatility 125 Day', 'Volatility'],
['Exchange Rate Sensitivity 52 Week XDR', 'Exchange Rate Sensitivity 52 Week XDR', 'Exchange Rate Sensitivity'],
['Exchange Rate Sensitivity 104 Week XDR', 'Exchange Rate Sensitivity 104 Week XDR', 'Exchange Rate Sensitivity'],
['Residual Gold Sensitivity 104 Week', 'Residual Gold Sensitivity 104 Week', 'Commodity Sensitivity'],
['Residual Oil Sensitivity 104 Week', 'Residual Oil Sensitivity 104 Week', 'Commodity Sensitivity'],
['Residual Gold Sensitivity 52 Week', 'Residual Gold Sensitivity 52 Week', 'Commodity Sensitivity'],
['Residual Oil Sensitivity 52 Week', 'Residual Oil Sensitivity 52 Week', 'Commodity Sensitivity'],
]
TRANSLATED_AXIOMA_CA4_FACTOR_NAMES={
}


AXIOMA_NA4_FACTOR_NAMES = [
['Amihud Liquidity 60 Day', 'Amihud Liquidity 60 Day', 'Liquidity'],
['Amihud Liquidity 125 Day', 'Amihud Liquidity 125 Day', 'Liquidity'],
['Book to Price Quarterly', 'Book to Price Quarterly', 'Value'],
['Cash Flow to Assets Annual', 'Cash Flow to Assets Annual', 'Profitability'],
['Cash Flow to Income Annual', 'Cash Flow to Income Annual', 'Profitability'],
['Debt to Assets Quarterly', 'Debt to Assets Quarterly', 'Leverage'],
['Debt to Equity Quarterly', 'Debt to Equity Quarterly', 'Leverage'],
['Dividend Yield Quarterly', 'Dividend Yield Quarterly', 'Cash Policy'],
['Earnings to Price Quarterly', 'Earnings to Price Quarterly', 'Value'],
['Est Earnings to Price Quarterly', 'Est Earnings to Price Quarterly', 'Value'],
['Earnings Growth Quarterly', '5 Year Earnings Growth', 'Growth'],
['Gross Margin Quarterly', 'Gross Margin Quarterly', 'Profitability'],
['Returns to Trading Days', 'Returns to Trading Days', 'Liquidity'],
['Log of Issuer Cap', 'Log of Issuer Cap', 'Size'],
['Log of 20-Day ADV to Issuer Cap', 'Log of 20-Day ADV to Issuer Cap', 'Liquidity'],
['Log of 60-Day ADV to Issuer Cap', 'Log of 60-Day ADV to Issuer Cap', 'Liquidity'],
['Annual Return Excl Prev Month', 'Annual Return Excl Prev Month', 'Momentum'],
['Monthly Return', 'Monthly Return', 'Momentum'],
['NA Regional Market Sensitivity 250 Day', 'NA Regional Market Sensitivity 250 Day', 'Volatility'],
['NA Regional Market Sensitivity 500 Day', 'NA Regional Market Sensitivity 500 Day', 'Volatility'],
['Return on Assets Quarterly', 'Return on Assets Quarterly', 'Profitability'],
['Return on Equity Quarterly', 'Return on Equity Quarterly', 'Profitability'],
['Sales to Assets Quarterly', 'Sales to Assets Quarterly', 'Profitability'],
['Sales Growth Quarterly', '5 Year Sales Growth', 'Growth'],
['NA Volatility 60 Day', 'NA Volatility 60 Day', 'Volatility'],
['NA Volatility 125 Day', 'NA Volatility 125 Day', 'Volatility'],
['Exchange Rate Sensitivity 52 Week XDR', 'Exchange Rate Sensitivity 52 Week XDR', 'Exchange Rate Sensitivity'],
['Exchange Rate Sensitivity 104 Week XDR', 'Exchange Rate Sensitivity 104 Week XDR', 'Exchange Rate Sensitivity'],
]
TRANSLATED_AXIOMA_NA4_FACTOR_NAMES={
}

AXIOMA_DMxUS4_FACTOR_NAMES = [
['Amihud Liquidity 60 Day', 'Amihud Liquidity 60 Day', 'Liquidity'],
['Amihud Liquidity 125 Day', 'Amihud Liquidity 125 Day', 'Liquidity'],
['Book to Price Annual', 'Book to Price Annual', 'Value'],
['Cash Flow to Assets Annual', 'Cash Flow to Assets Annual', 'Profitability'],
['Cash Flow to Income Annual', 'Cash Flow to Income Annual', 'Profitability'],
['Debt to Assets Annual', 'Debt to Assets Annual', 'Leverage'],
['Debt to Equity Annual', 'Debt to Equity Annual', 'Leverage'],
['Dividend Yield Annual', 'Dividend Yield Annual', 'Cash Policy'],
['Earnings to Price Annual', 'Earnings to Price Annual', 'Value'],
['Est Earnings to Price Annual', 'Est Earnings to Price Annual', 'Value'],
['Earnings Growth Annual', '5 Year Earnings Growth', 'Growth'],
['Gross Margin Annual', 'Gross Margin Annual', 'Profitability'],
['Returns to Trading Days', 'Returns to Trading Days', 'Liquidity'],
['Log of Issuer Cap', 'Log of Issuer Cap', 'Size'],
['Log of 20-Day ADV to Issuer Cap', 'Log of 20-Day ADV to Issuer Cap', 'Liquidity'],
['Log of 60-Day ADV to Issuer Cap', 'Log of 60-Day ADV to Issuer Cap', 'Liquidity'],
['Annual Return Excl Prev Month', 'Annual Return Excl Prev Month', 'Momentum'],
['Monthly Return', 'Monthly Return', 'Momentum'],
['DMxUS Regional Market Sensitivity 250 Day', 'DMxUS Regional Market Sensitivity 250 Day', 'Volatility'],
['DMxUS Regional Market Sensitivity 500 Day', 'DMxUS Regional Market Sensitivity 500 Day', 'Volatility'],
['Return on Assets Annual', 'Return on Assets Annual', 'Profitability'],
['Return on Equity Annual', 'Return on Equity Annual', 'Profitability'],
['Sales to Assets Annual', 'Sales to Assets Annual', 'Profitability'],
['Sales Growth Annual', '5 Year Sales Growth', 'Growth'],
['Volatility 60 Day', 'Volatility 60 Day', 'Volatility'],
['Volatility 125 Day', 'Volatility 125 Day', 'Volatility'],
['Exchange Rate Sensitivity 52 Week XDR', 'Exchange Rate Sensitivity 52 Week XDR', 'Exchange Rate Sensitivity'],
['Exchange Rate Sensitivity 104 Week XDR', 'Exchange Rate Sensitivity 104 Week XDR', 'Exchange Rate Sensitivity'],
]
TRANSLATED_AXIOMA_DMxUS4_FACTOR_NAMES={
}
